# Sponsor button of the repository: only platforms where the maintainer has an account
# (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)
patreon: IulianBondari
open_collective: iulian-bondari
ko_fi: iulianbondari
liberapay: IulianBondari
buy_me_a_coffee: iulianbondari
thanks_dev: u/gh/iulianbondari
