# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: IulianBondari
open_collective: iulian-bondari
ko_fi: iulianbondari
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: IulianBondari
issuehunt: iulian-bondari
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: iulianbondari
thanks_dev: iulianbondari
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
