//! Golden archives: fixed inputs (`tests/golden/inputs/`, generated by `make_inputs.py`) and the
//! archives that the v1 writers produced for them, kept for regression. Every v1 reader must open
//! them and restore the inputs bit-exact; the v1 writer must reproduce them byte for byte from the
//! same inputs and options (format freeze, `docs/V1-CONTRACT.md` §2). The set:
//!
//! | file | made by | options |
//! |---|---|---|
//! | `full-default.tsr` | full build | defaults (Lepton segments for the JPEG and the PDF image) |
//! | `lite-default.tsr` | lite build | defaults (JPEG stored as it is; identical to `pack --no-lepton` of the full build) |
//! | `canonical.tsr` | either | `--no-lepton --canonical` |
//! | `base.tsr`, `incremental.tsr` | either | `--no-lepton`; `incremental.tsr` packed with `--ref base.tsr` |
//! | `encrypted.tsr` | either | `--no-lepton --password golden --sign-key sign.key` (not deterministic: random key and nonces) |
//! | `volumes-2p1/`, `volumes-2p0/` | either | `volumes split full-default.tsr --data 2 --parity 1|0 --piece-size-kib 64` |

use std::path::{Path, PathBuf};
use tsaur_core::volumes::{self, SplitOptions};
use tsaur_core::{pack, Error, PackOptions, Reader};

fn golden() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests").join("golden")
}

fn temp(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("tsaur-golden-{}-{}-{}", tag, std::process::id(), std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

/// (archive path, bytes) of every committed input, sorted by path.
fn expected_inputs() -> Vec<(String, Vec<u8>)> {
    let root = golden().join("inputs");
    let mut out = Vec::new();
    let mut stack = vec![root.clone()];
    while let Some(dir) = stack.pop() {
        for e in std::fs::read_dir(&dir).unwrap() {
            let p = e.unwrap().path();
            if p.is_dir() {
                stack.push(p);
            } else {
                let rel = p.strip_prefix(&root).unwrap().to_string_lossy().replace('\\', "/");
                out.push((rel, std::fs::read(&p).unwrap()));
            }
        }
    }
    out.sort();
    assert_eq!(out.len(), 6, "the golden inputs are six files");
    out
}

fn assert_restored(dir: &Path, only: Option<&[&str]>) {
    for (rel, bytes) in expected_inputs() {
        if only.is_some_and(|list| !list.contains(&rel.as_str())) {
            continue;
        }
        assert_eq!(std::fs::read(dir.join(&rel)).unwrap_or_default(), bytes, "restored {rel} differs");
    }
}

fn no_lepton() -> PackOptions {
    PackOptions { jpeg_recompression: false, ..PackOptions::default() }
}

fn jpeg_entries(r: &Reader) -> Vec<usize> {
    r.entries().iter().enumerate().filter(|(_, e)| e.streams.as_ref().is_some_and(|s| s.segments.iter().any(|g| g.kind == tsaur_core::container::SEG_JPEG))).map(|(i, _)| i).collect()
}

#[test]
fn full_default_archive_restores_bit_exact_where_lepton_exists_and_reports_it_elsewhere() {
    let path = golden().join("full-default.tsr");
    let mut r = Reader::open(&path, None).unwrap();
    assert_eq!(r.entries().len(), 6);
    let jpeg = jpeg_entries(&r);
    assert_eq!(jpeg.len(), 2, "photo.jpg and paper.pdf carry Lepton segments");
    let out = temp("full");
    #[cfg(feature = "lepton")]
    {
        assert!(r.verify(None).unwrap().entries_bad.is_empty());
        r.extract(&out, None, false).unwrap();
        assert_restored(&out, None);
        // writer freeze: the same inputs and defaults give the same bytes
        let again = out.join("again.tsr");
        pack(std::slice::from_ref(&golden().join("inputs")), &again, PackOptions::default()).unwrap();
        assert_eq!(std::fs::read(&again).unwrap(), std::fs::read(&path).unwrap(), "the v1 writer no longer reproduces full-default.tsr");
    }
    #[cfg(not(feature = "lepton"))]
    {
        // the lite build names the entries it cannot decode and refuses the whole extraction
        let bad = r.verify(None).unwrap().entries_bad;
        assert_eq!(bad.len(), 2, "{bad:?}");
        assert!(bad.iter().all(|b| b.contains("Lepton")), "{bad:?}");
        let err = r.extract(&out, None, false).unwrap_err();
        assert!(matches!(err, Error::Invalid(_)) && err.to_string().contains("Lepton"), "{err}");
        // entries without JPEG content are still restored bit-exact
        let others: Vec<usize> = (0..r.entries().len()).filter(|i| !jpeg.contains(i)).collect();
        let out2 = temp("full-others");
        r.extract(&out2, Some(&others), false).unwrap();
        assert_restored(&out2, Some(&["notes.md", "random.bin", "report.docx", "sub/notes-v2.md"]));
        let _ = std::fs::remove_dir_all(&out2);
    }
    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn lite_default_archive_is_universal_and_equals_no_lepton_output_of_the_full_build() {
    let path = golden().join("lite-default.tsr");
    let mut r = Reader::open(&path, None).unwrap();
    assert!(jpeg_entries(&r).is_empty(), "no Lepton segments in the universal archive");
    assert!(r.verify(None).unwrap().entries_bad.is_empty());
    let out = temp("lite");
    r.extract(&out, None, false).unwrap();
    assert_restored(&out, None);
    let again = out.join("again.tsr");
    pack(std::slice::from_ref(&golden().join("inputs")), &again, no_lepton()).unwrap();
    assert_eq!(std::fs::read(&again).unwrap(), std::fs::read(&path).unwrap(), "pack --no-lepton must reproduce lite-default.tsr in every build");
    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn canonical_archive_keeps_originals_bit_exact_and_serves_views() {
    let path = golden().join("canonical.tsr");
    let mut r = Reader::open(&path, None).unwrap();
    assert_eq!(r.manifest.fidelity, "hybrid");
    let views: Vec<String> = r.entries().iter().filter(|e| e.derived.is_some()).map(|e| e.path.clone()).collect();
    assert!(views.iter().any(|v| v.ends_with("report.docx.md")) && views.iter().any(|v| v.ends_with("paper.pdf.txt")), "{views:?}");
    assert!(r.verify(None).unwrap().entries_bad.is_empty());
    let out = temp("canonical");
    let written = r.extract(&out, None, false).unwrap();
    assert_eq!(written.len(), 6, "views are not extracted by default");
    assert_restored(&out, None);
    let vi = r.entries().iter().position(|e| e.path.ends_with("report.docx.md")).unwrap();
    let mut buf = Vec::new();
    r.stream_entry(vi, &mut buf).unwrap();
    let text = String::from_utf8(buf).unwrap();
    assert!(text.contains("Golden report"), "{text}");
    let again = out.join("again.tsr");
    pack(std::slice::from_ref(&golden().join("inputs")), &again, PackOptions { canonical: true, ..no_lepton() }).unwrap();
    assert_eq!(std::fs::read(&again).unwrap(), std::fs::read(&path).unwrap(), "the v1 writer no longer reproduces canonical.tsr");
    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn incremental_archive_needs_its_reference_and_never_skips_silently() {
    let base = golden().join("base.tsr");
    let inc = golden().join("incremental.tsr");
    // without the reference: the archive opens (framing and manifest are self-contained) but
    // every entry that depends on external chunks fails verification and extraction with a
    // message that names the missing reference
    let mut alone = Reader::open(&inc, None).unwrap();
    assert!(alone.unresolved_external() > 0, "incremental.tsr must reference chunks it does not store");
    let bad = alone.verify(None).unwrap().entries_bad;
    assert!(!bad.is_empty() && bad.iter().all(|b| b.contains("reference")), "{bad:?}");
    let out = temp("inc-alone");
    let err = alone.extract(&out, None, false).unwrap_err();
    assert!(matches!(err, Error::Missing(_)), "{err}");
    assert!(std::fs::read_dir(&out).unwrap().all(|e| e.unwrap().path().is_dir()), "no unverified file may be left behind");
    // with the reference everything restores bit-exact
    let mut with = Reader::open_with_refs(&inc, None, std::slice::from_ref(&base)).unwrap();
    assert_eq!(with.unresolved_external(), 0);
    assert!(with.verify(None).unwrap().entries_bad.is_empty());
    let out2 = temp("inc-with");
    with.extract(&out2, None, false).unwrap();
    assert_restored(&out2, None);
    // freeze: base = inputs without sub/, incremental = everything against base
    let again_base = out2.join("base-again.tsr");
    let base_inputs: Vec<PathBuf> = ["notes.md", "random.bin", "report.docx", "paper.pdf", "photo.jpg"].iter().map(|n| golden().join("inputs").join(n)).collect();
    pack(&base_inputs, &again_base, no_lepton()).unwrap();
    assert_eq!(std::fs::read(&again_base).unwrap(), std::fs::read(&base).unwrap(), "the v1 writer no longer reproduces base.tsr");
    let again_inc = out2.join("inc-again.tsr");
    pack(std::slice::from_ref(&golden().join("inputs")), &again_inc, PackOptions { references: vec![base.clone()], ..no_lepton() }).unwrap();
    assert_eq!(std::fs::read(&again_inc).unwrap(), std::fs::read(&inc).unwrap(), "the v1 writer no longer reproduces incremental.tsr");
    let _ = std::fs::remove_dir_all(&out);
    let _ = std::fs::remove_dir_all(&out2);
}

#[test]
fn encrypted_signed_archive_unlocks_with_the_password_and_the_signature_verifies() {
    let path = golden().join("encrypted.tsr");
    let seed: [u8; 32] = hex::decode(std::fs::read_to_string(golden().join("sign.key")).unwrap().trim()).unwrap().try_into().unwrap();
    let pubkey = tsaur_core::crypto::sig::public_key(&seed);
    let info = tsaur_core::inspect(&path).unwrap();
    assert!(info.encrypted && info.signed, "{info:?}");
    assert!(matches!(Reader::open(&path, None), Err(Error::Crypto(_))), "no password: refused");
    assert!(matches!(Reader::open(&path, Some("wrong")), Err(Error::Crypto(_))), "wrong password: refused");
    let mut r = Reader::open(&path, Some("golden")).unwrap();
    let rep = r.verify(Some(&pubkey)).unwrap();
    assert!(rep.entries_bad.is_empty() && rep.signature_valid == Some(true), "{rep:?}");
    let other = tsaur_core::crypto::sig::public_key(&[7u8; 32]);
    assert_eq!(r.verify(Some(&other)).unwrap().signature_valid, Some(false), "a foreign public key must not verify the signature");
    let out = temp("enc");
    r.extract(&out, None, false).unwrap();
    assert_restored(&out, None);
    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn volumes_of_the_golden_archive_join_repair_and_are_reproducible() {
    let archive = std::fs::read(golden().join("full-default.tsr")).unwrap();
    let p1 = golden().join("volumes-2p1");
    let st = volumes::inspect(std::slice::from_ref(&p1), true).unwrap();
    assert_eq!(st.len(), 1);
    assert!(st[0].reconstructible && st[0].missing.is_empty());
    let vols: Vec<PathBuf> = st[0].volumes.iter().map(|v| v.as_ref().unwrap().path.clone()).collect();
    assert_eq!(vols.len(), 3);
    let out = temp("vol");
    // any two of the three volumes rebuild the archive bit-exact
    for drop in 0..3 {
        let keep: Vec<PathBuf> = vols.iter().enumerate().filter(|(i, _)| *i != drop).map(|(_, p)| p.clone()).collect();
        let joined = out.join(format!("joined-{drop}.tsr"));
        let rep = volumes::join(&keep, &joined).unwrap();
        assert!(rep.archive_hash_ok);
        assert_eq!(std::fs::read(&joined).unwrap(), archive);
    }
    // a lost volume is recreated byte-identical
    let repair_dir = out.join("repair");
    std::fs::create_dir_all(&repair_dir).unwrap();
    let rep = volumes::repair(&vols[..2], Some(&repair_dir)).unwrap();
    assert_eq!(rep.rebuilt.len(), 1);
    assert_eq!(std::fs::read(&rep.rebuilt[0].path).unwrap(), std::fs::read(&vols[2]).unwrap());
    // without parity, every volume that holds data is needed. The golden archive is smaller than
    // one 64 KiB piece, so the second data volume of the 2+0 set holds no piece at all: the first
    // volume alone rebuilds the archive, the (empty) second one alone cannot.
    let p0 = golden().join("volumes-2p0");
    let st0 = volumes::inspect(std::slice::from_ref(&p0), true).unwrap();
    assert!(st0[0].reconstructible && st0[0].set.parity == 0);
    assert_eq!((st0[0].set.volume_pieces(0), st0[0].set.volume_pieces(1)), (1, 0), "one piece in total");
    let v0: Vec<PathBuf> = st0[0].volumes.iter().map(|v| v.as_ref().unwrap().path.clone()).collect();
    assert!(volumes::join(&v0[1..], &out.join("half.tsr")).is_err(), "the empty volume alone holds no data");
    assert!(!out.join("half.tsr").exists(), "a failed join leaves no output file");
    assert_eq!(std::fs::read(volumes::join(&v0[..1], &out.join("first.tsr")).map(|_| out.join("first.tsr")).unwrap()).unwrap(), archive);
    assert_eq!(std::fs::read(volumes::join(&v0, &out.join("both.tsr")).map(|_| out.join("both.tsr")).unwrap()).unwrap(), archive);
    // split freeze: the same archive and geometry give byte-identical volumes
    let again = out.join("split-again");
    std::fs::create_dir_all(&again).unwrap();
    let rep = volumes::split(&golden().join("full-default.tsr"), &SplitOptions { data: 2, parity: 1, piece_size: Some(65536), outputs: vec![again.clone()] }).unwrap();
    for (v, orig) in rep.volumes.iter().zip(vols.iter()) {
        assert_eq!(std::fs::read(&v.path).unwrap(), std::fs::read(orig).unwrap(), "volume {} is no longer reproduced", orig.display());
    }
    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn future_format_versions_are_refused_not_misread() {
    let out = temp("version");
    // .tsr: header bytes 4..6 hold the version
    let mut bytes = std::fs::read(golden().join("lite-default.tsr")).unwrap();
    bytes[4..6].copy_from_slice(&2u16.to_le_bytes());
    let future = out.join("future.tsr");
    std::fs::write(&future, &bytes).unwrap();
    let err = match Reader::open(&future, None) {
        Err(e) => e,
        Ok(_) => panic!("an archive that declares version 2 was opened with v1 rules"),
    };
    assert!(matches!(err, Error::Version(2)), "{err}");
    assert!(err.to_string().contains("version 2"), "{err}");
    assert_eq!(err.exit_code(), 2);
    assert!(matches!(tsaur_core::inspect(&future), Err(Error::Version(2))));
    // .tsrv: a header that declares another version disables the volume even though its trailer is intact
    let p1 = golden().join("volumes-2p1");
    let src = std::fs::read_dir(&p1).unwrap().map(|e| e.unwrap().path()).find(|p| p.to_string_lossy().ends_with("v01.tsrv")).unwrap();
    let mut vb = std::fs::read(&src).unwrap();
    vb[4..6].copy_from_slice(&2u16.to_le_bytes());
    let vdir = out.join("vols");
    std::fs::create_dir_all(&vdir).unwrap();
    std::fs::write(vdir.join(src.file_name().unwrap()), &vb).unwrap();
    match volumes::inspect(std::slice::from_ref(&vdir), true) {
        Err(e) => assert!(matches!(e, Error::Missing(_)), "refused as no usable volume: {e}"),
        Ok(st) => assert!(st.is_empty() || st[0].volumes.iter().flatten().all(|v| !v.usable()), "a future-version volume must not be used: {st:?}"),
    }
    assert!(volumes::join(std::slice::from_ref(&vdir), &out.join("future-join.tsr")).is_err());
    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn unknown_manifest_keys_are_ignored() {
    // a v1.x writer may add keys; v1 readers must ignore them (CBOR map with an extra entry)
    let r = Reader::open(&golden().join("lite-default.tsr"), None).unwrap();
    let m = r.manifest.clone();
    assert_eq!(m.fidelity, "bit-exact");
    let mut v: ciborium::Value = ciborium::Value::serialized(&m).unwrap();
    if let ciborium::Value::Map(entries) = &mut v {
        entries.push((ciborium::Value::Text("future_key".into()), ciborium::Value::Integer(42.into())));
    } else {
        panic!("manifest encodes as a map");
    }
    let mut bytes = Vec::new();
    ciborium::into_writer(&v, &mut bytes).unwrap();
    let back: tsaur_core::manifest::Manifest = tsaur_core::format::cbor_decode(&bytes).unwrap();
    assert_eq!(back.fidelity, "bit-exact");
}
